openapi: "3.0.0"
info:
  description: ""
  version: "1.0.0"
  title: "Anna Project backend"

components:
  schemas:
    ResponseOK:
      type: object
      properties:
        status:
          type: string
          example: "ok"
        registration_id:
          type: string
          example: "07cff176-0bea-4bbb-9901-70ce82db8886"

    ResponseInvalidData:
      type: object
      properties:
        status:
          type: string
          example: "failed"
        message:
          type: string
          example: "invalid data"

    ResponseInvalidMethod:
      type: object
      properties:
        status:
          type: string
          example: "failed"
        message:
          type: string
          example: "Invalid method"

    ResponseOkGetStatus:
      properties:
        status:
          example: "orange"
          type: string
        beacon_ids:
          type: array
          items:
            type: object
            properties:
              date:
                description: "Date in format YYYYmmddhh"
                type: string
                example: "2020032810"
              beacon_id:
                description: "Single beacon id"
                type: string
                format: uuid
                example: "ce83fef9-470c-430f-b4c3-743c26373ab9"

    ResponseOkCheckVersion:
      properties:
        upgrade_required:
          example: false
          type: boolean
        upgrade_url:
          type: string
          format: uri

paths:
  /register_device/:
    post:
      tags:
      - "register"
      summary: "Request register device."
      description: ""
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - phone_no
              properties:
                phone_no:
                  type: string
                  description: "9 digit phone number with prefix +48"
                  example: "+48123123123"

      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseOK"
        405:
          description: "Invalid method"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ResponseInvalidMethod"
        422:
          description: "Invalid data"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ResponseInvalidData"
  /get_status/:
    post:
      tags:
        - "get_status"
      summary: "Get user status."
      description: ""
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseOkGetStatus"

  /check_version/:
    post:
      summary: "Check app status."
      description: ""
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseOkCheckVersion"
