openapi: "3.0.0"
info:
  description: ""
  version: "1.0.0"
  title: "Anna Project backend"

tags:
- name: "user"
  description: "User registration, authentication, authorization, etc."
components:
  schemas:
    ResponseOK:
      type: object
      properties:
        status:
          type: string
          example: "ok"

    ResponseInvalidData:
      type: object
      properties:
        status:
          type: string
          example: "failed"
        message:
          type: string
          example: "invalid data"

    ResponseInvalidMethod:
      type: object
      properties:
        status:
          type: string
          example: "failed"
        message:
          type: string
          example: "Invalid method"

    ResponseOKConfirmRegister:
      allOf:
        - $ref: "#/components/schemas/ResponseOK"
      properties:
        user_id:
          example: "07cff176-0bea-4bbb-9901-70ce82db8886"
          type: string


paths:
  /register_device/:
    post:
      tags:
      - "register"
      summary: "Request register device."
      description: ""
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - msisdn
              properties:
                msisdn:
                  type: string
                  description: "9 digit phone number with prefix +48"
                  example: "+48123123123"

      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseOK"
        405:
          description: "Invalid method"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ResponseInvalidMethod"
        422:
          description: "Invalid data"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ResponseInvalidData"

  /confirm_registration/:
    post:
      tags:
        - "register"
      summary: "Confirm register device."
      description: ""
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - msisdn
                - code
              properties:
                msisdn:
                  type: string
                  description: "9 digit phone number with prefix +48"
                  example: "+48123123123"
                code:
                  type: string
                  description: "code from sms"
                  example: "ASDFG"
                registration_id:
                  type: string
                  description: "code from sms"
                  example: "07cff176-0bea-4bbb-9901-70ce82db8886"

      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseOKConfirmRegister"
        405:
          description: "Invalid method"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ResponseInvalidMethod"
        422:
          description: "Invalid data"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ResponseInvalidData"
